name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: testing
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.20.1"

      - name: check format
        run: deno fmt --check

      - name: check lint
        run: deno lint

      - name: run tests
        run: deno test test/ --import-map=import_map.json